image: duduardo23/heroku-deploy:1

stages:
  - production
  
production:
  type: deploy
  stage: production
  image: duduardo23/heroku-deploy:1
  script:
    - dpl --provider=heroku --app=meudinheiro-edubarbieri --api-key=$HEROKU_API_KEY
  only:
    - master