const actionsTypes = {
  SHOW_BILL_ACTIONS: "SHOW_BILL_ACTIONS",
  SHOW_RECEIPT_ACTIONS: "SHOW_RECEIPT_ACTIONS",
  SHOW_EXTRACT_ACTIONS: "SHOW_EXTRACT_ACTIONS",
}

export const SHOW_BILL_ACTIONS = actionsTypes.SHOW_BILL_ACTIONS;
export const SHOW_RECEIPT_ACTIONS = actionsTypes.SHOW_RECEIPT_ACTIONS;
export const SHOW_EXTRACT_ACTIONS = actionsTypes.SHOW_EXTRACT_ACTIONS;
export default actionsTypes;